---
title: "Matemáticas básicas"
subtitle: "Números reales y complejos"
author: "Ricardo Michel MALLQUI BAÑOS"
institute: "Universidad Nacional San Cristóbal De Huamanga"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: krantz
link-citations: yes
subparagraph: yes
colorlinks: yes
fontsize: 16pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
lot: yes
lof: yes
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
toc_appendix: yes
description: ""
---

```{=tex}
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\CC}{\mathbb{C}}
\newcommand{\I}{\mathbb{I}}
\newcommand{\f}{\mathbb{f}}
\newcommand{\X}{\mathbb{X}}
\newcommand{\D}{\mathbb{D}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\norm}[1]{\left\Vert#1\right\Vert}
\newcommand{\abs}[1]{\left\vert#1\right\vert}
\newcommand{\set}[1]{\left\{#1\right\}}
\newcommand{\seq}[1]{\left<#1\right>}
\newcommand{\co}[1]{\left[#1\right]}
\newcommand{\cc}[1]{\left(#1\right)}
\newcommand{\J}{\mathcal{J}}
\newcommand{\K}{\mathcal{K}}
\newcommand{\M}{\mathcal{M}}
\newcommand{\F}{\mathcal{F}}
```
# Resumen {.unnumbered}

La asignatura de Matemáticas Básicas forma parte del grupo de asignaturas básicas de primer curso, en todas las instituciones la cual tiene como objetivo principal desarrollar la capacidad de la resolución de problemas matemáticos sencillos que pueden plantearse en la escuela. Este carácter básico de la asignatura le confiere un papel clave en la formación de futuros egresados.

Este libro se divie en 9 capitulos: Logica, conjuntos, funciones y relaciones, numeros reales, funciones exponenciales y logaritmicas, induccion matematica, susceciones, numeros complejos, polinomios. Los cuales se desarrollarán conjuntas a ejemplos y ejercicios.

# Introducción {.unnumbered}

La matemática es una ciencia lógica deductiva, que utiliza símbolos para generar una teoría exacta de deducción e inferencia basada en definiciones, axiomas, postulados y reglas que transforman elementos primitivos en relaciones y teoremas más complejos. Esta ciencia enseña al individuo a pensar de una manera lógica y por lo tanto a desarrollar habilidades a resolver problemas y tomar decisiones. Las habilidades numéricas son valoradas por la mayoría de los sectores, se puede decir que en algunos casos son considerados esenciales.

La asignatura de Matemáticas Básicas forma parte del grupo de asignaturas básicas de primer curso, en todas las instituciones la cual tiene como objetivo principal desarrollar la capacidad de la resolución de problemas matemáticos sencillos que pueden plantearse en la escuela. Este carácter básico de la asignatura le confiere un papel clave en la formación de futuros egresados.

Capacidad para la resolución de los problemas matemáticos que puedan plantearse en la ingeniería. Aptitud para aplicar los conocimientos sobre: álgebra lineal; geometría; geometría diferencial; cálculo diferencial e integral; ecuaciones diferenciales y en derivadas parciales; métodos numéricos; algorítmica numérica; estadística y optimización.

 Que los estudiantes hayan demostrado poseer y comprender conocimientos en un área de estudio que parte de la base de la educación secundaria general, y se suele encontrar a un nivel que, si bien se apoya en libros de texto avanzados, incluye también algunos aspectos que implican conocimientos procedentes de la vanguardia de su campo de estudio.

 Capacidad para utilizar herramientas informáticas de búsqueda de recursos bibliográficos o de información relacionada con las telecomunicaciones y la electrónica. Resultados de aprendizaje (Objetivos formativos):

 * Conocimiento de materias básicas y tecnologías, que le capacite para el aprendizaje de nuevos métodos y tecnologías, así como que le dote de una gran versatilidad para adaptarse a nuevas situaciones.
 * Capacidad de resolver problemas con iniciativa, toma de decisiones, creatividad, y de comunicar y transmitir conocimientos, habilidades y destrezas, comprendiendo la responsabilidad ética y profesional de la actividad del Ingeniero/a Técnico de Telecomunicación.
